travis:
  secure:
    BINSTAR_TOKEN: jVBs5I5lltZIKHLHocF9ABIKuOBAcQnv7bFJbJRIGuDR/e6QXukvkbyKOM9/T3IlGfLZyDdrBYfx1Ik7nAxUe11cOIIq4nouQDMkpqiQnYxfuv4pIKTndbw8fDNz/G8oXn9ha1SV/GvEehDCrKeYEL/YE1cMJluAKTD8F9pVuyCAWlio96TN+cbEFCwimAi6VCo91lW9G7MkY7ybIpxzyCmOpFmfk36i3h/+XvIM10Xo76tCjRkhdXC7gL2KySCZo6WOrn9nc8MxCZyQC01pwamQxHfUUIe5PyZ2qBQZekxbpP5no9xTJJL8Huv29Xnf2h1hSGg7ACzWp1Oi1RfHnjdWUA+69OzLfOSBDgxKTRMbpJ+IRDRtOx5Ll5VxenPwjBRFzWROsO3BVB/Rjmm8bs0sc/yakz2QwNRjZDLe551ZhmdcuMvH0vBsPjtQsWLHIbioC+IyBkOgkEBvUINnezyUkICB7OTsxNtsG802Ug2r27gCOLf7lI9eq1XnC2yK6r9lDlnZpnJ0vtf46A1i0dF0ECel+ckaiNsDDdSa5/DKDkVZKIyb3p6cjDxeopL6UVyWXOCoUS3mof5zKDYw0Su3PufDykiFcpBZHJjT7FSHzMFzolons6/MKcFNGcbkKRWg2ot0Ld28aTnRhDlCjo8WaM+45LidqF6Ezn1KwDc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
